---
kind: pipeline
name: AS Email Django App Tests

steps:
  - name: test
    image: "python:3.11"
    environment:
      PYTHONUNBUFFERED: 1
    commands:
      - pip install -r ./requirements/development.txt
      - cd ./app/
      - mkdir ./staticfiles
      - python ./manage.py collectstatic --clear --no-input --verbosity 0
      - pytest

---
kind: pipeline
name: Build Notify

steps:
  - name: slack notification
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_notify_webhook
      channel: builds
      username: drone
