version: '3'

volumes:
  redis_data:
    name: "as_email_redis_data_01"

services:
  web: &web
    image: "as_email_service_app:${RELEASE_VERSION}"
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod
    ports:
      - "11578:8000"
    command: /app/scripts/start_app.sh
    restart: always
    env_file: .env
    volumes:
      - "${HOST_DB_DIR}:/mnt/db:z"
      - "${HOST_SPOOL_ROOT}:/mnt/spool:z"
      - "${HOST_MAIL_ROOT}:/mnt/mail_dirs:z"
    profiles:
      - prod

  devweb:
    <<: *web
    image: as_email_service_app_dev
    container_name: app_dev
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    depends_on:
      - mailhog
    ports:
      - "11578:8000"
    command: /app/manage.py runserver_plus 0.0.0.0:8000
    restart: always
    env_file: .env
    volumes:
      - ./app:/app:z
      - "${HOST_DB_DIR}:/mnt/db:z"
      - "${HOST_SPOOL_ROOT}:/mnt/spool:z"
      - "${HOST_MAIL_ROOT}:/mnt/mail_dirs:z"
      - type: bind
        source: ./pyproject.toml
        target: /app/pyproject.toml
        read_only: true
    profiles:
      - dev

  smtpd:
    image: as_email_service_app
    container_name: smtpd
    ports:
      - "586:586"
    command: /app/scripts/start_smtpd.sh
    restart: always
    env_file: .env
    volumes:
      - "${HOST_DB_DIR}:/mnt/db:z"
      - "${HOST_SPOOL_ROOT}:/mnt/spool:z"
      - "${HOST_MAIL_ROOT}:/mnt/mail_dirs:z"
      - "${HOST_SSL_DIR}:/mnt/ssl:ro"
    profiles:
      - dev
      - prod

  worker:
    image: as_email_service_app
    container_name: worker
    command: /app/scripts/start_worker.sh
    restart: always
    env_file: .env
    volumes:
      - "${HOST_DB_DIR}:/mnt/db:z"
      - "${HOST_SPOOL_ROOT}:/mnt/spool:z"
      - "${HOST_MAIL_ROOT}:/mnt/mail_dirs:z"
    profiles:
      - dev
      - prod

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - "redis_data:/data"
      - type: bind
        source: ${PWD}/config/redis/redis.conf
        target: /usr/local/etc/redis/redis.conf
    expose:
      - 6379
    profiles:
      - dev
      - prod

  mailhog:
    image: druidfi/mailhog:1.0.1
    container_name: mailhog
    ports:
      - "8025:8025"
    profiles:
      - dev
