# Generated by Django 5.2.15 on 2026-06-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_userinvitation_invitee_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinvitation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                    ("reset_sent", "Password Reset Sent"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
    ]
