# Generated by Django 4.2.3 on 2023-07-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("as_email", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="incoming_spool_dir",
            field=models.CharField(
                blank=True,
                help_text="The directory incoming messages are temporarily spooled to before being delivered. If not set a reasonable default will be chosen (this is the recommended way).",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="mail_dir_parent",
            field=models.CharField(
                blank=True,
                help_text="The directory that is the root of all the local mailboxes that mail will be delivered to if being delivered locally. The mailboxes are named by the email address being delivered to.If not set a reasonable default will be chosen (this is the recommended way).",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="outgoing_spool_dir",
            field=models.CharField(
                blank=True,
                help_text="The directory outgoing messages are temporarily spooled to before being sent to the server for delivery. If not set a reasonable default will be chosen (this is the recommended way).",
                max_length=1024,
                null=True,
            ),
        ),
    ]
