# Generated by Django 4.2.4 on 2023-08-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("as_email", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailaccount",
            name="forward_style",
            field=models.CharField(
                choices=[("EN", "Encapsulate"), ("RS", "Resend")],
                default="RS",
                help_text="When forwarding email to an address outside of the system you canchoose two ways to format the message. Either encapsualte it as anrfc822 mime attchment, or send the message on, rewriting the from: address, and adding text to the message indicating it was resent. In all cases the forwarded message will have `resent-from`and `reply-to` headers added so that replies go to the original address.",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="emailaccount",
            name="deactivated",
            field=models.BooleanField(
                default=False,
                help_text="If an account is deactivated it can still receive email. However it is no longer allowed to send email. Also, no forwarding or aliasing is allowed. All email received by a deactivated account is delivered locally.",
            ),
        ),
    ]
