# Generated by Django 4.2.2 on 2023-06-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("as_email", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="emailaccount",
            name="as_email_em_address_dcaef1_idx",
        ),
        migrations.RemoveField(
            model_name="emailaccount",
            name="address",
        ),
        migrations.AddField(
            model_name="emailaccount",
            name="email_address",
            field=models.EmailField(
                default="none@example.com",
                help_text="The email address that will receive emails on this server, and the address that will be used as a login to send emails. It must have the same domin name as the associated server",
                max_length=254,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="emailaccount",
            name="deactivated",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="emailaccount",
            name="deactivated_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason for the account being deactivated",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="emailaccount",
            index=models.Index(
                fields=["email_address"], name="as_email_em_email_a_7ad406_idx"
            ),
        ),
    ]
