# Generated by Django 4.2.3 on 2023-07-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("as_email", "0002_alter_server_incoming_spool_dir_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailaccount",
            name="handle_blocked_messages",
            field=models.CharField(
                choices=[("BL", "Block"), ("DE", "Deliver")],
                default="DE",
                help_text="When the email provider blocks a message because it is thought to be spam you can choose to have the email delivered to the folder set in the `blocked messages delivery folder` or you canchoose them to be blocked. ie: not delivered to your mail box at all. They will be viewable in the email account's blocked messages list where you can choose to have them delivered to your mail box on a message by message basis.",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="emailaccount",
            name="mail_dir",
            field=models.CharField(
                blank=True,
                help_text="The root folder of the mail directory for this email account. This should be left blank and it will be auto-filled in when the email account is created. Only fill it in if you have a specific location in the file system you want this user's mailbox to be stored at.",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="emailaccount",
            name="password",
            field=models.CharField(
                default="XXX",
                help_text="Password used for the SMTP and IMAP services for this email account",
                max_length=200,
            ),
        ),
    ]
