# Generated by Django 4.2.4 on 2023-08-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("as_email", "0002_emailaccount_forward_style_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailaccount",
            name="deactivated",
            field=models.BooleanField(
                default=False,
                help_text="If an account is deactivated it can still receive email. However it is no longer allowed to send email. Aliasing to other email accounts is allowed, but no forwarding to an email account not on on the system is allowed.",
            ),
        ),
    ]
