# Generated by Django 4.2.2 on 2023-07-07 20:38

import as_email.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "as_email",
            "0002_remove_emailaccount_as_email_em_address_dcaef1_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="incoming_spool_dir",
            field=models.FilePathField(
                allow_files=False,
                allow_folders=True,
                default="/mnt/spool/incoming",
                max_length=1000,
                recursive=True,
                verbose_name=as_email.models.spool_dir_path,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="server",
            name="mail_dir_parent",
            field=models.FilePathField(
                allow_files=False,
                allow_folders=True,
                default="/mnt/maildir",
                max_length=1000,
                recursive=True,
                verbose_name=as_email.models.email_base_dir,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="server",
            name="outgoing_spool_dir",
            field=models.FilePathField(
                allow_files=False,
                allow_folders=True,
                default="/mnt/spool/outgoing",
                max_length=1000,
                recursive=True,
                verbose_name=as_email.models.spool_dir_path,
            ),
            preserve_default=False,
        ),
    ]
