# Generated by Django 5.0.2 on 2024-03-04 03:07

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("as_email", "0003_alter_emailaccount_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailaccount",
            name="imap_account",
            field=models.CharField(
                blank=True,
                help_text="The account to authenticate for on the specified IMAP Server",
                max_length=256,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="emailaccount",
            name="imap_auth",
            field=django_cryptography.fields.encrypt(
                models.CharField(
                    blank=True,
                    help_text="The authentication token to use for for authenticating the IMAP account. Typically a password but might be some other kind of token.",
                    max_length=1024,
                    null=True,
                )
            ),
        ),
        migrations.AddField(
            model_name="emailaccount",
            name="imap_server",
            field=models.CharField(
                blank=True,
                help_text="The <domain name>:<port> of the IMAP server to deliver email to",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="emailaccount",
            name="delivery_method",
            field=models.CharField(
                choices=[
                    ("LD", "Local"),
                    ("IM", "IMAP"),
                    ("AL", "Alias"),
                    ("FW", "Forwarding"),
                ],
                default="LD",
                help_text="Delivery method indicates how email for this account is delivered. This is either delivery to a local mailbox, delivery to an IMAP mailbox, an alias to another email account on this system or forwarding to an email address by encapsulating the message or rewriting the headers.",
                max_length=2,
            ),
        ),
    ]
