# Generated by Django 4.2.3 on 2023-08-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "as_email",
            "0003_alter_emailaccount_handle_blocked_messages_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailaccount",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("LD", "Local Delivery"),
                    ("AL", "Alias"),
                    ("FW", "Forwarding"),
                ],
                default="LD",
                max_length=2,
            ),
        ),
        migrations.AddIndex(
            model_name="blockedmessage",
            index=models.Index(
                fields=["created_at", "email_account"],
                name="as_email_bl_created_56a090_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="blockedmessage",
            index=models.Index(
                fields=["status", "email_account"],
                name="as_email_bl_status_9eeea7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="messagefilterrule",
            index=models.Index(
                fields=["email_account", "order"],
                name="as_email_me_email_a_8a8dcb_idx",
            ),
        ),
    ]
