# Generated by Django 5.0.6 on 2024-07-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("as_email", "0003_alter_emailaccount_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messagefilterrule",
            name="header",
            field=models.CharField(
                choices=[
                    ("addr", "addr"),
                    ("*", "*"),
                    ("bcc", "bcc"),
                    ("cc", "cc"),
                    ("default", "default"),
                    ("x-dspam-result", "x-dspam-result"),
                    ("from", "from"),
                    ("reply-to", "reply-to"),
                    ("source", "source"),
                    ("x-spam-score", "x-spam-score"),
                    ("x-spam-status", "x-spam-status"),
                    ("subject", "subject"),
                    ("to", "to"),
                ],
                default="default",
                max_length=32,
            ),
        ),
    ]
