# Generated by Django 4.2.3 on 2023-07-26 00:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "as_email",
            "0003_server_incoming_spool_dir_server_mail_dir_parent_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="messagefilterrule",
            unique_together={("email_account", "header", "pattern")},
        ),
    ]
