# Generated by Django 4.2.3 on 2023-07-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("as_email", "0004_alter_messagefilterrule_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="messagefilterrule",
            old_name="folder",
            new_name="destination",
        ),
        migrations.AlterField(
            model_name="messagefilterrule",
            name="action",
            field=models.CharField(
                choices=[("folder", "folder"), ("destroy", "destroy")],
                default="folder",
                max_length=10,
            ),
        ),
    ]
