# Generated by Django 4.2.3 on 2023-08-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("as_email", "0004_alter_emailaccount_account_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blockedmessage",
            options={"ordering": ("email_account", "created_at")},
        ),
        migrations.AlterModelOptions(
            name="emailaccount",
            options={"ordering": ("server", "email_address")},
        ),
        migrations.AlterModelOptions(
            name="server",
            options={"ordering": ("domain_name",)},
        ),
        migrations.AddIndex(
            model_name="emailaccount",
            index=models.Index(
                fields=["server"], name="as_email_em_server__cd7056_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="server",
            index=models.Index(
                fields=["domain_name"], name="as_email_se_domain__7128d9_idx"
            ),
        ),
    ]
