# Generated by Django 4.2.3 on 2023-07-26 03:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        (
            "as_email",
            "0005_rename_folder_messagefilterrule_destination_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="messagefilterrule",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="messagefilterrule",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
