# Generated by Django 5.2.7 on 2025-10-23 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("as_email", "0005_add_provider_backend_support"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="server",
            name="provider",
        ),
    ]
