# Generated by Django 4.2.3 on 2023-08-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("as_email", "0005_alter_blockedmessage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="api_key",
            field=models.CharField(
                default="12345",
                help_text="In order for the server to be able to post data to the web hooks provided by this service, they need an API key that is unique to this server.",
                max_length=40,
            ),
            preserve_default=False,
        ),
    ]
