# Generated by Django 4.2.4 on 2023-08-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("as_email", "0006_server_api_key"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="emailaccount",
            name="as_email_em_user_id_0589fd_idx",
        ),
        migrations.RenameField(
            model_name="emailaccount",
            old_name="user",
            new_name="owner",
        ),
        migrations.AddIndex(
            model_name="emailaccount",
            index=models.Index(
                fields=["owner"], name="as_email_em_owner_i_3e0f16_idx"
            ),
        ),
    ]
