# Generated by Django 5.2.7 on 2025-11-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("as_email", "0006_remove_old_provider_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailaccount",
            name="delivery_method",
            field=models.CharField(
                choices=[
                    ("LD", "LOCAL_DELIVERY"),
                    ("AL", "ALIAS"),
                    ("FW", "FORWARDING"),
                ],
                default="LD",
                help_text="Delivery method indicates how email for this account is delivered. This is either delivery to a local mailbox, delivery to an IMAP mailbox, an alias to another email account on this system or forwarding to an email address by encapsulating the message or rewriting the headers.",
                max_length=2,
            ),
        ),
    ]
