# Generated by Django 4.2.4 on 2023-08-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "as_email",
            "0007_remove_emailaccount_as_email_em_user_id_0589fd_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="smtp_server",
            field=models.CharField(
                default="smtp.postmarkapp.com",
                help_text="The host:port for sending messages via SMTP for this provider (each server has its own unique login, but all the servers on the same provider using the same hostname for SMTP.)",
                max_length=200,
            ),
            preserve_default=False,
        ),
    ]
