# Generated by Django 5.2.7 on 2025-11-16 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("as_email", "0007_alter_emailaccount_delivery_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailaccount",
            name="server",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_accounts",
                to="as_email.server",
            ),
        ),
    ]
