# Generated by Django 4.2.5 on 2023-09-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "as_email",
            "0007_rename_blocked_messages_delivery_folder_emailaccount_spam_delivery_folder_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailaccount",
            old_name="spam_assassin_score_threshold",
            new_name="spam_score_threshold",
        ),
        migrations.AlterField(
            model_name="emailaccount",
            name="autofile_spam",
            field=models.BooleanField(
                default=True,
                help_text="When incoming mail exceeds the threshold set in `spam_score_threshold` then this email will automatically files in the `spam_delivery_folder` mailbox. NOTE: This only apply if local or IMAP delivery is selected in `delivery_method`.",
            ),
        ),
    ]
