# Generated by Django 5.2.7 on 2025-11-18 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("as_email", "0006_remove_old_provider_field"),
    ]

    operations = [
        # Remove the old delivery_method CharField
        migrations.RemoveField(
            model_name="emailaccount",
            name="delivery_method",
        ),
        # Create the new DeliveryMethod model
        migrations.CreateModel(
            name="DeliveryMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[("LD", "Local Delivery"), ("AL", "Alias")],
                        help_text="The type of delivery method",
                        max_length=2,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        help_text="Type-specific configuration for this delivery method. Contents vary by delivery_type.",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Execution order (lower numbers execute first)",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this delivery method is active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "email_account",
                    models.ForeignKey(
                        help_text="The email account this delivery method belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_methods",
                        to="as_email.emailaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "indexes": [
                    models.Index(
                        fields=["email_account", "enabled"],
                        name="as_email_de_email_a_3e1ffb_idx",
                    ),
                    models.Index(
                        fields=["email_account", "order"],
                        name="as_email_de_email_a_844245_idx",
                    ),
                ],
            },
        ),
    ]
