# Generated by Django 4.2.5 on 2023-09-29 07:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "as_email",
            "0008_rename_spam_assassin_score_threshold_emailaccount_spam_score_threshold_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailaccount",
            name="forward_style",
        ),
    ]
