# Generated by Django 4.2.4 on 2023-08-21 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("as_email", "0008_provider_smtp_server"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_email_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="as_email.emailaccount",
                    ),
                ),
                (
                    "to_email_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="as_email.emailaccount",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="emailaccount",
            name="alias_for",
            field=models.ManyToManyField(
                related_name="aliases",
                related_query_name="alias",
                through="as_email.Alias",
                to="as_email.emailaccount",
            ),
        ),
        migrations.AddConstraint(
            model_name="alias",
            constraint=models.UniqueConstraint(
                fields=("from_email_account", "to_email_account"),
                name="as_email_alias_unique_relationships",
            ),
        ),
        migrations.AddConstraint(
            model_name="alias",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("from_email_account", models.F("to_email_account")),
                    _negated=True,
                ),
                name="as_email_alias_prevent_self_alias",
            ),
        ),
    ]
