# Generated by Django 5.2.7 on 2026-02-23 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("as_email", "0008_alter_emailaccount_server"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="When disabled, this delivery method is skipped during message delivery.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="emailaccount",
            name="enabled",
            field=models.BooleanField(
                default=True,
                help_text="If an account is not enabled, email for this account will not be accepted. This is equivalent to the email account not existing.",
            ),
        ),
        migrations.CreateModel(
            name="LocalDelivery",
            fields=[
                (
                    "deliverymethod_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="as_email.deliverymethod",
                    ),
                ),
                (
                    "maildir_path",
                    models.CharField(
                        blank=True,
                        help_text="Root folder for the local MH mailbox. Left blank it will be auto-filled from the account's email address when first saved.",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "autofile_spam",
                    models.BooleanField(
                        default=True,
                        help_text="When enabled, messages above the spam score threshold are automatically filed in the spam delivery folder.",
                    ),
                ),
                (
                    "spam_delivery_folder",
                    models.CharField(
                        default="Junk",
                        help_text="Folder to deliver spam into when autofile_spam is enabled.",
                        max_length=1024,
                    ),
                ),
                (
                    "spam_score_threshold",
                    models.IntegerField(
                        default=15,
                        help_text="Messages with an X-Spam-Score at or above this value are considered spam. 15 is a reasonable default.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Local Delivery",
                "verbose_name_plural": "Local Deliveries",
            },
            bases=("as_email.deliverymethod",),
        ),
        migrations.AddField(
            model_name="deliverymethod",
            name="email_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_methods",
                to="as_email.emailaccount",
            ),
        ),
        migrations.AddField(
            model_name="deliverymethod",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.CreateModel(
            name="AliasToDelivery",
            fields=[
                (
                    "deliverymethod_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="as_email.deliverymethod",
                    ),
                ),
                (
                    "target_account",
                    models.ForeignKey(
                        help_text="The EmailAccount messages will be aliased to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliased_from",
                        to="as_email.emailaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alias-To Delivery",
                "verbose_name_plural": "Alias-To Deliveries",
            },
            bases=("as_email.deliverymethod",),
        ),
    ]
