# Generated by Django 4.2.3 on 2023-07-26 06:34

import as_email.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("as_email", "0008_alter_server_incoming_spool_dir_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="incoming_spool_dir",
            field=models.CharField(
                default=as_email.models.spool_dir_path,
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="mail_dir_parent",
            field=models.CharField(
                default=as_email.models.email_base_dir,
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="outgoing_spool_dir",
            field=models.CharField(
                default=as_email.models.spool_dir_path,
                max_length=1024,
                null=True,
            ),
        ),
    ]
