# Generated by Django 4.2.5 on 2023-10-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("as_email", "0009_remove_emailaccount_forward_style"),
    ]

    operations = [
        migrations.CreateModel(
            name="InactiveEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(
                        help_text="The inactive email address. Our mail provider has indicate that we are not allowed to send emails to this address anymore.",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "can_activate",
                    models.BooleanField(
                        default=False,
                        help_text="If True this indicates that we are able to manually reactivate sending emails to this address. Before doing so we need to make sure that any problems sending to this address have been resolved.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("email_address",),
                "indexes": [
                    models.Index(
                        fields=["email_address"],
                        name="as_email_in_email_a_e60072_idx",
                    ),
                    models.Index(
                        fields=["can_activate"],
                        name="as_email_in_can_act_803305_idx",
                    ),
                    models.Index(
                        fields=["email_address", "can_activate"],
                        name="as_email_in_email_a_6918c2_idx",
                    ),
                ],
            },
        ),
    ]
