# Generated by Django 5.2.7 on 2026-03-03 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("as_email", "0012_backfill_polymorphic_ctype"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailaccount",
            name="scan_incoming_spam",
            field=models.BooleanField(
                default=True,
                help_text="When enabled, incoming email is scanned by SpamAssassin and X-Spam-* headers are added. When disabled, provider-injected spam headers are preserved without rescanning (if they exist).",
            ),
        ),
        migrations.AlterField(
            model_name="localdelivery",
            name="spam_score_threshold",
            field=models.IntegerField(
                default=5,
                help_text="Messages with an X-Spam-Score at or above this value are considered spam. 5 is a reasonable default.",
            ),
        ),
    ]
