# Generated by Django 4.2.6 on 2023-10-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("as_email", "0012_alter_messagefilterrule_email_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="api_key",
            field=models.CharField(
                blank=True,
                help_text="In order for the mail provider to be able to post data to the web hooks on this service, they need an API key that is unique to this server. NOTE: This is for incoming posts FROM the mail server to this service. NOT for authenticating this service to the provider. If this is left blank it will have a sufficiently random string generated.",
                max_length=40,
                null=True,
            ),
        ),
    ]
