# Generated by Django 5.2.7 on 2026-03-03 23:25

import django.db.models.deletion
import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("as_email", "0013_emailaccount_scan_incoming_spam_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImapDelivery",
            fields=[
                (
                    "deliverymethod_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="as_email.deliverymethod",
                    ),
                ),
                (
                    "imap_host",
                    models.CharField(
                        help_text="Hostname of the remote IMAP server.",
                        max_length=253,
                    ),
                ),
                (
                    "imap_port",
                    models.PositiveIntegerField(
                        default=993,
                        help_text="IMAP port (default 993 for IMAPS).",
                    ),
                ),
                (
                    "username",
                    encrypted_fields.fields.EncryptedCharField(
                        help_text="IMAP login username. Stored encrypted at rest.",
                        max_length=254,
                    ),
                ),
                (
                    "password",
                    encrypted_fields.fields.EncryptedCharField(
                        help_text="IMAP login password. Stored encrypted at rest.",
                        max_length=1024,
                    ),
                ),
                (
                    "autofile_spam",
                    models.BooleanField(
                        default=True,
                        help_text="When enabled, messages whose X-Spam-Score meets or exceeds the threshold are filed in the server's Junk folder instead of INBOX.",
                    ),
                ),
                (
                    "spam_score_threshold",
                    models.IntegerField(
                        default=5,
                        help_text="Messages with an X-Spam-Score at or above this value are considered spam. 5 is a reasonable default.",
                    ),
                ),
            ],
            options={
                "verbose_name": "IMAP Delivery",
                "verbose_name_plural": "IMAP Deliveries",
            },
            bases=("as_email.deliverymethod",),
        ),
    ]
