# Generated by Django 5.2.7 on 2026-03-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("as_email", "0014_imapdelivery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imapdelivery",
            name="autofile_spam",
            field=models.BooleanField(
                default=True,
                help_text="When enabled, messages whose spam score (from X-Spam-Status) meets or exceeds the threshold are filed in the server's Junk folder instead of INBOX.",
            ),
        ),
        migrations.AlterField(
            model_name="imapdelivery",
            name="spam_score_threshold",
            field=models.IntegerField(
                default=5,
                help_text="Messages with a spam score (from X-Spam-Status) at or above this value are considered spam. 5 is a reasonable default.",
            ),
        ),
        migrations.AlterField(
            model_name="localdelivery",
            name="spam_score_threshold",
            field=models.IntegerField(
                default=5,
                help_text="Messages with a spam score (from X-Spam-Status) at or above this value are considered spam. 5 is a reasonable default.",
            ),
        ),
    ]
