# Generated by Django 5.2.15 on 2026-07-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("as_email", "0016_set_default_site_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="mail_hostname",
            field=models.CharField(
                blank=True,
                help_text="The hostname advertised to email clients for both IMAP and SMTP in the autoconfig/autodiscover responses for this domain. If not set, settings.SITE_NAME is used. Unlike the spool/mail_dir fields above, this is resolved at request time, not filled in when the Server is created -- so it always reflects the current settings.SITE_NAME until a domain-specific override is set here.",
                max_length=200,
                null=True,
            ),
        ),
    ]
